name: Deploy to Ubuntu Server

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build app
        run: go build -o app .

      - name: Debug whoami
        run: whoami

      - name: Deploy binary
        run: |
          sudo -n systemctl stop api-books
          cp ./app /home/ferytell/API-Golang-Books/app
          sudo -n systemctl start api-books
      - name: Restart service
        run: |
          sudo systemctl restart api-books
          sudo systemctl status api-books --no-pager -l
